# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFiles@2
  inputs:
    contents: '**'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure for Students' # Ensure this matches your service connection name in Azure DevOps
    appName: 'Fardeen-Portfolio-website'    # Ensure this matches your Azure Web App name
    package: '$(Build.ArtifactStagingDirectory)/drop'

- script: |
    result=$(curl -s -o /dev/null -w "%{http_code}" https://Fardeen-Portfolio-website.azurewebsites.net)
    if [ "$result" == "200" ]; then
      echo "Website is live"
    else
      echo "Website is not accessible. HTTP Status: $result"
      exit 1
  displayName: 'Check Website Status'