# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

The pipeline is failing because the `npm run build --if-present` and `npm run test --if-present` commands cannot find the `package.json` file in the repository. Here's the relevant error message from the logs:

```
npm error code ENOENT
npm error syscall open
npm error path /home/runner/work/Portfolio_website/Portfolio_website/package.json
npm error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/home/runner/work/Portfolio_website/Portfolio_website/package.json'
npm error enoent This is related to npm not being able to find a file.
```

This error indicates that the `package.json` file is missing or not located in the expected directory.

### Steps to Resolve:

1. **Check `package.json` Location**:
   - Ensure that the `package.json` file exists in the root directory of your repository.

2. **Update Pipeline Configuration**:
   - If the `package.json` file is in a sub-directory, update the pipeline configuration to navigate to the correct directory before running npm commands.

Here's an example of how you might update your pipeline YAML file to navigate to a sub-directory (if applicable):

```yaml
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFiles@2
  inputs:
    contents: '**'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'

- script: |
    cd path/to/sub-directory  # Change to the directory containing package.json
    npm install
    npm run build --if-present
    npm run test --if-present
  displayName: 'Install and Build'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure for Students'
    appName: 'Fardeen-Portfolio-website'
    package: '$(Build.ArtifactStagingDirectory)/drop'

- script: |
    result=$(curl -s -o /dev/null -w "%{http_code}" https://Fardeen-Portfolio-website.azurewebsites.net)
    if [ "$result" == "200" ]; then
      echo "Website is live"
    else
      echo "Website is not accessible. HTTP Status: $result"
      exit 1
  displayName: 'Check Website Status'
```

Verify that the `package.json` file is in the correct location and update the pipeline script accordingly. This should resolve the `ENOENT` error and allow the build to proceed.
